import type { Metadata } from 'next'
import '@/style/style.scss'
import Header from "@/components/layout/header/HeaderContainer"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">      
      <body>
      <Header />
      <div className='Contents'>
          {children}
      </div>
      </body>
    </html>
  )
}
